# Site settings
title: "Ame Perdue"
description: "To all lost souls waiting to be found. Scarred hearts looking foward to get healed."
baseurl: ""
url: "http://cham26.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: 
  - title: "git"
    url: http://cham26.github.io/
  - title: "rss"
    url: /feed.xml
