# Site settings
title: "Plein D'espoir"
description: "To all lost souls waiting to be found. To scarred hearts looking foward to get healed. To tears willing to be parched. To a new hope ready to celebrate life and embrace happiness."
baseurl: ""
url: "http://cham26.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: 
  - title: "git"
    url: http://cham26.github.io/
  - title: "rss"
    url: /feed.xml
